config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :strains
  resources :primers
  resources :plasmids  

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plasmid.rb
require 'csv'

class Plasmid < ApplicationRecord


  def self.to_csv
    attributes = %w{name source method sequence_validated reference}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |plasmid|
        csv << attributes.map{ |attr| plasmid.send(attr) }
      end
    end
  end

end

app/models/primer.rb
require 'csv'

class Primer < ApplicationRecord
  
  def self.to_csv
    attributes = %w{name sequence}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |primer|
        csv << attributes.map{ |attr| primer.send(attr) }
      end
    end
  end
  
end

app/models/strain.rb
require 'csv'

class Strain < ApplicationRecord

  def self.to_csv
    attributes = %w{accession common_name keywords strain_background source method Mutant_source_DNA upstream_check_primers downstream_check_primers reference sequence_validated general_info genotype ploidy phenotype}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |strain|
        csv << attributes.map{ |attr| strain.send(attr) }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plasmids_controller.rb
class PlasmidsController < ApplicationController

http_basic_authenticate_with name: "omearalab", password: "example", except: [:index, :show]

  def index
    @plasmids = Plasmid.all
    
    respond_to do |format|
      format.html
      format.csv { send_data @plasmids.to_csv, filename: "plasmids-#{Date.today}.csv" }
    end
  end

  def show
    @plasmid = Plasmid.find(params[:id])
  end

  def new
  end

  def edit
    @plasmid = Plasmid.find(params[:id])
  end

  def create
    @plasmid = Plasmid.new(plasmid_params)
    @plasmid.save
    redirect_to @plasmid
  end

  def update
    @plasmid = Plasmid.find(params[:id])

    if @plasmid.update(plasmid_params)
      redirect_to @plasmid
    else
      render 'edit'
    end
  end

  def destroy
    @plasmid = Plasmid.find(params[:id])
    @plasmid.destroy
    redirect_to plasmids_path
  end

  
  private
    def plasmid_params
      params.require(:plasmid).permit(
        :name,
        :source,
        :method,
        :sequence_validated,
        :reference)
    end
end

app/controllers/primers_controller.rb
class PrimersController < ApplicationController

http_basic_authenticate_with name: "omearalab", password: "example", except: [:index, :show]

  def index
    @primers = Primer.all

    respond_to do |format|
      format.html
      format.csv { send_data @primers.to_csv, filename: "primers-#{Date.today}.csv" }
    end
  end

  def show
    @primer = Primer.find(params[:id])
  end

  def new
  end

  def edit
    @primer = Primer.find(params[:id])
  end

  def create
    @primer = Primer.new(primer_params)
    @primer.save
    redirect_to @primer
  end

  def update
    @primer = Primer.find(params[:id])

    if @primer.update(primer_params)
      redirect_to @primer
    else
      render 'edit'
    end
  end

  def destroy
    @primer = Primer.find(params[:id])
    @primer.destroy
    redirect_to primers_path
  end

  
  private
    def primer_params
      params.require(:primer).permit(
        :name,
        :sequence)
    end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController

http_basic_authenticate_with name: "omearalab", password: "example", except: [:index, :show]

  def index
    @strains = Strain.all

    respond_to do |format|
      format.html
      format.csv { send_data @strains.to_csv, filename: "strains-#{Date.today}.csv" }
    end
  end

  def show
    @strain = Strain.find(params[:id])
  end

  def new
  end

  def edit
    @strain = Strain.find(params[:id])
  end

  def create
    @strain = Strain.new(strain_params)
    @strain.save
    redirect_to @strain
  end

  def update
    @strain = Strain.find(params[:id])

    if @strain.update(strain_params)
      redirect_to @strain
    else
      render 'edit'
    end
  end

  def destroy
    @strain = Strain.find(params[:id])
    @strain.destroy
    redirect_to strains_path
  end

  
  private
    def strain_params
      params.require(:strain).permit(
        :accession,
        :common_name,
        :strain_background,
        :general_info,
        :source,
        :keywords,
        :genotype,
        :phenotype,
        :ploidy,
        :reference,
        :sequence_validated,
        :method,
        :Mutant_source_DNA,
        :upstream_check_primers,
        :downstream_check_primers)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plasmids_helper.rb
module PlasmidsHelper
end

app/helpers/primers_helper.rb
module PrimersHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StrainLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plasmids/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>


<h1>Edit plasmid</h1>

<%= form_with(model: @plasmid, local: true) do |form| %>
<div class="container">
  <div class="row">
    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Identifiers</h4>
	</div>
	<div class="panel-body">
	  <%= form.label :name %>
	  <%= form.text_field :name, :required => true %> </br>
	</div>
      </div>
      <br>
      <br>
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Source</h4>
	</div>
	<div class="panel-body">
	  <%= form.label :source %>
	  <%= form.select :source, ['O\'Meara Lab', 'Other Lab'], :required => true %> </br>

	  <!--show if TOMeara Lab -->
	  <br>
	  Fill these in if O'Meara lab was selected:<br>
	  <%= form.label :method %>
	  <%= form.text_field :method %> </br>

	  <!--show if Other Lab -->
	  <br>
	  Fill these in if Other Lab was selected:<br>
	  <%= form.label :reference %>
	  <%= form.text_field :reference %> </br>

	  </br>
	  </br>
	  <%= form.label :sequence_validated %>
	  <%= form.text_field :sequence_validated %> </br>

	</div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-lg">
      <center>
      <h2><%= form.submit %></h2>
      </center>
    </div>
  </div>
</div>


<% end %>

<hr>
<%= link_to 'Back to plasmid page', plasmids_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/plasmids/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>

<div class="jumbotron text-center">
  <h1>Lab Fungal Plasmids</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <table class="table table-striped table-hover">
        <thead>
	  <tr>
            <th scope="col"><b>Name</b></th>
	    <th></th>
	    <th></th>
	    <th scope="col"> Download:
	      <%= link_to 'csv', plasmids_path(format: "csv") %>
	    </th>
	  </tr>
        </thead>
        <tbody>
          <% @plasmids.each do |plasmid| %>
          <tr>
            <td><%= plasmid.name %></td>
            <td><%= link_to 'Show', plasmid_path(plasmid) %></td>
            <td><%= link_to 'Edit', edit_plasmid_path(plasmid) %></td>
	    <td><%= link_to 'Destroy', plasmid_path(plasmid),
		    method: :delete,
		    data: {confirm: 'Are you sure?'} %></td>
          </tr>
          <% end %>
	</tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <center>
	<h4> Add a <%= link_to 'new plasmid', new_plasmid_path %> to the database </h4>
      </center>
    </div>
</div>


<hr>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/plasmids/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>


<h1>New plasmid</h1>

<%= form_with scope: :plasmid, url:plasmids_path, local: true do |form| %>
<div class="container">
  <div class="row">
    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Identifiers</h4>
	</div>
	<div class="panel-body">
	  <%= form.label :name %>
	  <%= form.text_field :accession, :required => true %> </br>
	</div>
      </div>
      <br>
      <br>
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Source</h4>
	</div>
	<div class="panel-body">
	  <%= form.label :source %>
	  <%= form.select :source, ['O\'Meara Lab', 'Other Lab'], :required => true %> </br>

	  <!--show if TOMeara Lab -->
	  <br>
	  Fill these in if O'Meara lab was selected:<br>
	  <%= form.label :method %>
	  <%= form.text_field :method %> </br>
	  
	  <!--show if Other Lab -->
	  <br>
	  Fill these in if Other Lab was selected:<br>
	  <%= form.label :reference %>
	  <%= form.text_field :reference %> </br>

	  <br>
	  <br>	  
	  <%= form.label :sequence_validated %>
	  <%= form.text_field :sequence_validated %> </br>
	  
	</div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-sm">
      <center>
      <h2><%= form.submit %></h2>
      </center>
    </div>
  </div>
</div>


<% end %>

<hr>
<%= link_to 'Back to plasmid page', plasmids_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/plasmids/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>

<div class="container">
  <div class="row">
    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Identifiers</h4>
	</div>
	<div class="panel-body">
	  <span class="font-weight-bold">Name:</span> <%= @plasmid.name %> </br>
	</div>
      </div>
      <br>
      <br>
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Source</h4>
	</div>
	<div class="panel-body">

	  <span class="font-weight-bold">Souce:</span> <%= @plasmid.source %> </br>

	  <!--show if TOMeara Lab -->
	  <span class="font-weight-bold">Method:</span> <%= @plasmid.method %> </br>

	  <!--show if Other Lab -->	  
          <span class="font-weight-bold">Reference:</span> <%= @plasmid.reference %> </br>
	  </br>
	  </br>
          <span class="font-weight-bold">Sequence Validated:</span> <%= @plasmid.sequence_validated %> </br>
	</div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm text-right">
      <h3>
	<%= link_to 'Edit Plasmid', edit_plasmid_path(@plasmid) %>
      </h3>
    </div>
  </div>
</div>


<hr>
<%= link_to 'Back to plasmid page', plasmids_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/primers/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>


<h1>Edit primer</h1>

<%= form_with(model: @primer, local: true) do |form| %>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <%= form.label :name %>
      <%= form.text_field :name, :required => true %> </br>

      <%= form.label :sequence %>
      <%= form.text_area :sequence, :rows => 10, :required => true %> </br>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-lg">
      <center>
      <h2><%= form.submit %></h2>
      </center>
    </div>
  </div>
</div>


<% end %>

<hr>
<%= link_to 'Back to primer page', primers_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/primers/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>

<div class="jumbotron text-center">
  <h1>Lab Primers</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <table class="table table-striped table-hover">
        <thead>
	  <tr>
            <th scope="col"><b>Name</b></th>
	    <th></th>
	    <th></th>
	    <th scope="col"> Download:
	      <%= link_to 'csv', primers_path(format: "csv") %>
	    </th>
	  </tr>
        </thead>
        <tbody>
          <% @primers.each do |primer| %>
          <tr>
            <td><%= primer.name %></td>
            <td><%= link_to 'Show', primer_path(primer) %></td>
            <td><%= link_to 'Edit', edit_primer_path(primer) %></td>
	    <td><%= link_to 'Destroy', primer_path(primer),
		    method: :delete,
		    data: {confirm: 'Are you sure?'} %></td>
          </tr>
          <% end %>
	</tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <center>
	<h4> Add a <%= link_to 'new primer', new_primer_path %> to the database </h4>
      </center>
    </div>
</div>


<hr>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/primers/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>


<h1>New primer</h1>

<%= form_with scope: :primer, url:primers_path, local: true do |form| %>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <%= form.label :name %>
      <%= form.text_field :name, :required => true %> </br>

      <%= form.label :sequence %>
      <%= form.text_area :sequence, :rows => 10, :required => true %> </br>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-sm">
      <center>
      <h2><%= form.submit %></h2>
      </center>
    </div>
  </div>
</div>


<% end %>

<hr>
<%= link_to 'Back to primer page', primers_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/primers/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>

<div class="container">
  <div class="row">
    <div class="col-lg">
      <span class="font-weight-bold">Name:</span>
      <%= @primer.name %> </br>

      <span class="font-weight-bold">Sequence:</span><br>
      <%= @primer.sequence %> </br>
    </div>
  </div>
  <div class="row">
    <div class="col-sm text-right">
      <h3>
	<%= link_to 'Edit Primer', edit_primer_path(@primer) %>
      </h3>
    </div>
  </div>
</div>


<hr>
<%= link_to 'Back to primer page', primers_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/strains/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>


<h1>Edit strain</h1>

<%= form_with(model: @strain, local: true) do |form| %>
<div class="container">
  <div class="row">
    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Identifiers</h4>
	</div>
	<div class="panel-body">
	  <div class="form-group">
	    <%= form.label :accession %>
	    <%= form.text_field :accession, :required => true %>
	  </div>

	  <div class="form-group">
	    <%= form.label :common_name %>
	    <%= form.text_field :common_name, :required => true %>
	  </div>

	  <div class="form-group">
	    <%= form.label :keywords %>
	    <%= form.text_field :keywords %>
	  </div>
	  
	</div>
      </div>
      <br>
      <br>
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Source</h4>
	</div>
	<div class="panel-body">
	  <div class="form-group">
	    <%= form.label :strain_background %>
	    <%= form.text_field :strain_background, :required => true%>
	  </div>

	  <br>
	  
	  <div class="form-group">
	    <%= form.label :source %>
	    <%= form.select :source, ['O\'Meara Lab', 'Other Lab'], :required => true %>
	  </div>
	  
	  <!--show if TOMeara Lab -->
	  <div class="form-group" id="strain_method_group">
	    <%= form.label :method %>
	    <%= form.text_field :method %>
	  </div>

	  <div class="form-group" id="strain_Mutant_source_DNA_group">
	    <%= form.label :Mutant_source_DNA %>
	    <%= form.text_field :Mutant_source_DNA %>
	  </div>

	  <div class="form-group" id="strain_upstream_check_primers_group">
	    <%= form.label :upstream_check_primers %>
	    <%= form.text_field :upstream_check_primers %>
	  </div>

	  <div class="form-group" id="strain_downstream_check_primers_group">
	    <%= form.label :downstream_check_primers %>
	    <%= form.text_field :downstream_check_primers %>
	  </div>

	  <!--show if Other Lab -->
	  <div class="form-group" id="strain_reference_group">	  
	    <%= form.label :reference %>
	    <%= form.text_field :reference %>
	  </div>

	  <div class="form-group" id="strain_sequence_validated_group">  
	    <%= form.label :sequence_validated %>
	    <%= form.text_field :sequence_validated %>
	  </div>

	</div>
      </div>
    </div>

    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Characterization</h4>
	</div>
	<div class="panel-body">

	  <div class="form-group">
	    <%= form.label :general_info %><br>
	    <%= form.text_area :general_info, :rows => 5, :required => true %>
	  </div>

	  <div class="form-group">
	    <%= form.label :genotype %>
	    <%= form.text_field :genotype, :required => true %>
	  </div>

	  <div class="form-group">
	    <%= form.label :ploidy %>
	    <%= form.text_field :ploidy, :required => true %>
	  </div>

	  <div class="form-group">
	    <%= form.label :phenotype %>
	    <%= form.text_field :phenotype %>
	  </div>
	</div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-lg">
      <center>
      <h2><%= form.submit %></h2>
      </center>
    </div>
  </div>
</div>


<% end %>

<hr>
<%= link_to 'Back to strain page', strains_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/strains/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>

<div class="jumbotron text-center">
  <h1>Lab Fungal Strains</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <table class="table table-striped table-hover">
        <thead>
	  <tr>
            <th scope="col"><b>Accession</b></th>
            <th scope="col"><b>Common Name</b></th>
	    <th></th>
	    <th></th>
	    <th scope="col"> Download:
	      <%= link_to 'csv', strains_path(format: "csv") %>
	    </th>
	  </tr>
        </thead>
        <tbody>
          <% @strains.each do |strain| %>
          <tr>
            <td><%= strain.accession %></td>
            <td><%= strain.common_name %></td>
            <td><%= link_to 'Show', strain_path(strain) %></td>
            <td><%= link_to 'Edit', edit_strain_path(strain) %></td>
	    <td><%= link_to 'Destroy', strain_path(strain),
		    method: :delete,
		    data: {confirm: 'Are you sure?'} %></td>
          </tr>
          <% end %>
	</tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <center>
	<h4> Add a <%= link_to 'new strain', new_strain_path %> to the database </h4>
      </center>
    </div>
</div>


<hr>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/strains/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>


<h1>New strain</h1>

<%= form_with scope: :strain, url:strains_path, local: true do |form| %>
<div class="container">
  <div class="row">
    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Identifiers</h4>
	</div>
	<div class="panel-body">
	  <%= form.label :accession %>
	  <%= form.text_field :accession, :required => true %> </br>

	  <%= form.label :common_name %>
	  <%= form.text_field :common_name, :required => true %> </br>

	  <%= form.label :keywords %>
	  <%= form.text_field :keywords %> </br>
	</div>
      </div>
      <br>
      <br>
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Source</h4>
	</div>
	<div class="panel-body">
	  <%= form.label :strain_background %>
	  <%= form.text_field :strain_background, :required => true %> </br>

	  <%= form.label :source %>
	  <%= form.select :source, ['O\'Meara Lab', 'Other Lab'], :required => true %> </br>

	  <!--show if TOMeara Lab -->
	  <br>
	  Fill these in if O'Meara lab was selected:<br>
	  <%= form.label :method %>
	  <%= form.text_field :method %> </br>
	  
	  <%= form.label :Mutant_source_DNA %>
	  <%= form.text_field :Mutant_source_DNA %> </br>

	  <%= form.label :upstream_check_primers %>
	  <%= form.text_field :upstream_check_primers %> </br>

	  <%= form.label :downstream_check_primers %>
	  <%= form.text_field :downstream_check_primers %> </br>

	  <!--show if Other Lab -->
	  <br>
	  Fill these in if Other Lab was selected:<br>
	  <%= form.label :reference %>
	  <%= form.text_field :reference %> </br>

	  <%= form.label :sequence_validated %>
	  <%= form.text_field :sequence_validated %> </br>
	</div>
      </div>
    </div>

    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Genomic characterization</h4>
	</div>
	<div class="panel-body">
	  <%= form.text_area :general_info, :rows => 5, :required => true %> </br>

	  <%= form.label :genotype %>
	  <%= form.text_field :genotype, :required => true %> </br>

	  <%= form.label :ploidy %>
	  <%= form.text_field :ploidy, :required => true %> </br>

	  <%= form.label :phenotype %>
	  <%= form.text_field :phenotype %> </br>
	</div>
      </div>
      <br>
      <br>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-sm">
      <center>
      <h2><%= form.submit %></h2>
      </center>
    </div>
  </div>
</div>


<% end %>

<hr>
<%= link_to 'Back to strain page', strains_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/strains/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>    
  
</nav>

<div class="container">
  <div class="row">
    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Identifiers</h4>
	</div>
	<div class="panel-body">
	  <span class="font-weight-bold">Accession:</span> <%= @strain.accession %> </br>
          <span class="font-weight-bold">Common Name:</span> <%= @strain.common_name %> </br>
          <span class="font-weight-bold">keywords:</span> <%= @strain.keywords %> </br>
	</div>
      </div>
      <br>
      <br>
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Source</h4>
	</div>
	<div class="panel-body">
	  <span class="font-weight-bold">Strain Background:</span> <%= @strain.strain_background %> </br>
	  <span class="font-weight-bold">Source:</span> <%= @strain.source %> </br>


	  <!--show if TOMeara Lab -->
	  <span class="font-weight-bold">Method:</span> <%= @strain.method %> </br>
	  <span class="font-weight-bold">Mutant source DNA:</span> <%= @strain.Mutant_source_DNA %> </br>
          <span class="font-weight-bold">upstream_check_primers:</span> <%= @strain.upstream_check_primers %> </br>
          <span class="font-weight-bold">downstream_check_primers:</span> <%= @strain.downstream_check_primers %> </br>

	  <!--show if Other Lab -->	  
          <span class="font-weight-bold">Reference:</span> <%= @strain.reference %> </br>
          <span class="font-weight-bold">Sequence Validated:</span> <%= @strain.sequence_validated %> </br>
	</div>
      </div>
    </div>

    <div class="col-md">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <h4>Genomic characterization</h4>
	</div>
	<div class="panel-body">
	  <span class="font-weight-bold">General Info:</span></br>
	  <p><%= @strain.general_info %></p> </br>
          <span class="font-weight-bold">Genotype:</span> <%= @strain.genotype %> </br>
          <span class="font-weight-bold">Ploidy:</span> <%= @strain.ploidy %> </br>
          <span class="font-weight-bold">Phenotype:</span> <%= @strain.phenotype %> </br>
	</div>
      </div>
      <br>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-sm text-right">
      <h3>
	<%= link_to 'Edit Strain', edit_strain_path(@strain) %>
      </h3>
    </div>
  </div>
</div>


<hr>
<%= link_to 'Back to strain page', strains_path %>
<br>
<%= link_to 'Back to main page', welcome_index_path %>

app/views/welcome/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <span>
    <h2>
    <a href='http://https://omeara.lab.medicine.umich.edu/'>
      Teresa O'Meara Lab
    </a>
    </h2>
  </span>      
</nav>

<div class="jumbotron text-center">
  <h1>Lab Fungal Strains</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <h3> This database contains information about research artifacts that have been used by the O'Meara lab. Please keep it up-to-date.</h3>
      </br>
      </br>
      <h4> View the <%= link_to 'Strains', controller: 'strains' %> table </h4>
      <h4> View the <%= link_to 'Primers', controller: 'primers' %> table </h4>
      <h4> View the <%= link_to 'Plasmids', controller: 'plasmids' %> table </h4>
    </div>
  </div>
</div>